FROM registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7

WORKDIR /ocr

COPY *.py .
COPY server.sh .

# CPU use command below
RUN python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

# CUDA9 or CUDA 10 use command below
# RUN python3 -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple

RUN pip install "paddleocr>=2.0.1" "scikit-learn" -i https://mirror.baidu.com/pypi/simple
RUN chmod +x /ocr/server.sh

EXPOSE 8080

CMD ["/ocr/server.sh"]